title: Peters Lab
description: Peters Lab at Oxford University
baseurl: "/"
url: ""

email: peters.andrew.j@gmail.com
twitter: flickerfusion
googlescholar: kJ_SaH8AAAAJ
orcid: 0000-0001-9351-1456
github: PetersNeuroLab

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
images-people: '/assets/images/people'
papers: '/papers'
files: '/assets/files'
